version: '2.1'

services:
  dm-print-web:
    image: robol/dm-print-web
    ports:
      - 5000:5000
    environment:
      - "DM_PRINT_PRINTSERVER=printserver.dm.unipi.it"
      - "DM_PRINT_ALLOWED_PRINTERS=cdc11,cdcpp,cdcpt"
